Lib index
khanzf/opengit pull request #14
Opened 2019-06-13 06:37 UTC by khanzf

This reads the .git/index file (called the cache by GPL git).
There is a lot of string manipulation that could be cleaned up, but please verify that there are no overt problems.

2019-06-13 23:50 UTC, ibara requested changes

2019-06-13 23:50 UTC, ibara commented on lib/index.c
> +tree_entry(unsigned char *indexmap, long *offset, int extsize)
`off_t`, not `long`

2019-06-13 23:50 UTC, ibara commented on lib/index.c
> +dirc_entry(unsigned char *indexmap, long *offset, int entries)
Same thing here. `off_t`, not `long`.

2019-06-14 09:00 UTC, khanzf commented on lib/index.c
> +tree_entry(unsigned char *indexmap, long *offset, int extsize)
Thank you!

2019-06-14 09:00 UTC, khanzf commented on lib/index.c
> +dirc_entry(unsigned char *indexmap, long *offset, int entries)
Again, thank you for the review.

2019-06-14 09:03 UTC, merged